"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Ticket } from "lucide-react"
import { useSession } from "next-auth/react"

export function HallTicketsPage() {
  const { data: session } = useSession()
  return (
    <div className="p-4 md:p-6 space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-gray-900">Hall Tickets</h2>
        <p className="text-sm text-gray-500 mt-1">Generate and download examination hall tickets</p>
      </div>
      <Card className="border-0 shadow-sm">
        <CardContent className="flex flex-col items-center justify-center py-16 gap-4">
          <div className="w-16 h-16 rounded-2xl bg-[#1a3a6b]/10 flex items-center justify-center">
            <Ticket className="size-8 text-[#1a3a6b]" />
          </div>
          <div className="text-center">
            <h3 className="font-semibold text-gray-900">Hall Tickets</h3>
            <p className="text-sm text-gray-500 mt-1">Hall tickets will be generated by the examination section and made available here before the exam.</p>
          </div>
          <Badge className="bg-amber-100 text-amber-700 border-amber-200">Upcoming: November 2024 Examinations</Badge>
        </CardContent>
      </Card>
    </div>
  )
}
